
set nocompatible
silent function! OSX()
  return has('macunix')
endfunction

silent function! LINUX()
  return has('unix') && !has('macunix') && !has('win32unix')
endfunction

silent function! WINDOWS()
  return  (has('win16') || has('win32') || has('win64'))
endfunction

let mapleader="\<Space>"

" Thirdparty stuff
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linters = {
      \ 'haskell': ['hlint'],
      \}
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_balloons = 1

let g:airline#extensions#ale#enabled = 1
let g:airline_powerline_fonts = 1

" let g:syntastic_haskell_checkers=['hlint']
" let g:syntastic_cpp_checkers=['clang_check']
" let g:syntastic_cpp_clang_check_post_args=''
" let g:syntastic_r_checkers=['lintr']
" let g:syntastic_r_lintr_linters="with_defaults(line_length_linter(120))"
" let g:syntastic_enable_r_lintr_checker=1

let g:polyglot_disabled = ['haskell']
let g:ledger_bin="hledger"

let g:rainbow_active=1
let g:coc_disable_startup_warning=1

filetype off

""""" My stuff
syntax enable
set hlsearch

filetype plugin indent on

set background=dark
if has("gui_running")
  let g:solarized_contrast="high"
else
  let g:solarized_contrast="low"
endif
colorscheme solarized

"let loaded_matchparen=1 " Do not show matching parens

set bs=2                " Allow backspacing over everything in insert mode
set cursorline
" set complete=.,w,b,u    " Word completion rules
set relativenumber      " Relative line numbers

set showmatch
set shiftwidth=2
set tabstop=2
set expandtab
set shiftround
set smartindent

set nowrap
set scrolloff=2
set sidescroll=1
set sidescrolloff=5
set laststatus=2

set foldmethod=indent   " Set folding method
set foldlevelstart=99   " Do not fold by default
set wildignore=*.fasl,*.o,*.class,*.hi,*.pyc,*.so,*.exe

set formatoptions=tcroq " Formatting options
set nobackup            " Do not keep a backup file
set viminfo='20,<500,"500   " read/write a .viminfo file -- limit regs to 500 lines
set history=50          " keep 50 lines of command history
set ruler               " Show the cursor position all the time
set guioptions=c
set autoread
set shortmess=aTI
set splitbelow
set splitright

let g:python_recommended_style=0

" Load matchit.vim, but only if the user hasn't installed a newer version.
if has("packages")
  packadd! matchit
elseif !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
 runtime! macros/matchit.vim
endif

" Don't use Ex mode, use Q for formatting
map Q gq

set noerrorbells
set visualbell
set t_vb=
autocmd GUIEnter * set visualbell t_vb=

set t_ti=
set t_te=

if WINDOWS()
  set encoding=utf-8
  set fileencoding=utf-8
  set guifont=Source\ Code\ Pro
else
  " set guifont=Source\ Code\ Pro
  " set guifont=Anonymous\ Pro
  " set guifont=Droid\ Sans\ Mono
end

if &term =~ '^screen'
  " 0,1 -> blinking block
  " 2 -> solid block
  " 3 -> blinking underscore
  " 4 -> solid underscore
  " normal mode
  let &t_EI .= "\<Esc>[0 q"
  " insert mode
  let &t_SI .= "\<Esc>[6 q"
endif

set grepprg="rg --vimgrep"
let g:ackprg="rg --vimgrep"
set grepformat=%f:%l:%c:%m
" reload as china encoding
nnoremap <leader>cn :edit ++enc=gb18030<CR>
nnoremap } }zz
nnoremap { {zz
nnoremap <leader>ag :Ack<Space>

nnoremap <leader>o :FZF<CR>
