#!/bin/sh

# keymaps
sysmodmap=/etc/X11/xinit/.Xmodmap
usermodmap=$HOME/.Xmodmap
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# merge in defaults
sysresources=/etc/X11/xinit/.Xresources
userresources=$HOME/.Xresources
solarizedres=$HOME/thirdparty/style/solarized-xresources/Xresources.dark
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$solarizedres" ] && xrdb -merge "$solarizedres"

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

NUM_MONITORS=$(xrandr --listactivemonitors | grep '^Monitors' | cut -d: -f2)
echo "NUM_MONITORS=$NUM_MONITORS"
if [ "$NUM_MONITORS" -gt 1 ]; then
  echo "xrandr --output eDP1 --primary --below DP1"
fi

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
# dbus-launch --sh-syntax --exit-with-session > /dev/null
fcitx

exec "$HOME/.local/bin/xmonad-x86_64-linux"
