#! /usr/bin/env zsh

function executable() { which $1 >> /dev/null && [[ -x `which $1` ]] }
function isosx() { [[ `uname` = 'Darwin' ]] }
function init_path() {
  typeset -a bins
  if isosx; then
    bins=($HOME/Library/Python/2.7/bin /usr/local/sbin)
  else
    bins=($HOME/.local/bin)
  fi
  typeset -gU path; path=($HOME/bin $bins $HOME/.cabal/bin $path $HOME/code/prcore)
}
function init_aws() {
  local AWS_CONFIG=$HOME/etc/aws-config.ini
  [[ -f $AWS_CONFIG ]] && export AWS_CONFIG_FILE=$AWS_CONFIG
}

init_path
init_aws

typeset -T -U PYTHONPATH pythonpath
pythonpath=($HOME/code/prcore $pythonpath)
export PYTHONPATH
export JAVA_HOME=/usr
export LANG=en_US.UTF-8
export HISTSIZE=10000

limit coredumpsize unlimited
limit datasize 1024m
limit addressspace "$(( 16 * 1024 ))m"

NVM_DIR=$HOME/thirdparty/js/nvm
NVM_VER=v0.10.21
[[ -s $NVM_DIR/nvm.sh ]] && source $NVM_DIR/nvm.sh && { nvm use "$NVM_VER" || nvm install "$NVM_VER" } &> /dev/null
# if [[ -e $HOME/.nix-profile/etc/profile.d/nix.sh ]]; then
#   source $HOME/.nix-profile/etc/profile.d/nix.sh
#   manpath=($HOME/.nix-profile/share/man $manpath)
# fi
