#! /usr/bin/env

# oh my zsh
# git clone http://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
ZSH=$HOME/thirdparty/oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(git git-prompt svn cabal colored-man colorize brew)
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"
source $ZSH/oh-my-zsh.sh

# my stuff
autoload zmv
export LESS="-FRSX --tabs=2"
export EDITOR="vim"

# use  oh-my-zsh for now
#bindkey -v
#bindkey '^R' history-incremental-pattern-search-backward
function _wrap_sp() { if [[ -z $1 ]] then echo ''; else echo "$1 "; fi }
PROMPT='%{$fg[blue]%}%D{[%I:%M:%S]} %{$fg[white]%}%2~ $(_wrap_sp $(prompt_git_info))%{$fg_bold[blue]%}%#%{$reset_color%} '
RPS1="%{$fg_bold[green]%}%n@%m %{$reset_color%}"

alias lt='ll -rt'
alias ccat='colorize'
if isosx; then
  alias myproc='ps -u $USER -f'
  alias showHidden='defaults write com.apple.finder AppleShowAllFiles YES'
  alias hideHidden='defaults write com.apple.finder AppleShowAllFiles NO'
else
  alias myproc='ps -u $USER uf'
fi

# unset from oh-my-zsh
unsetopt inc_append_history
unsetopt share_history
# my opts
setopt NO_BEEP
setopt EXTENDED_GLOB
setopt CORRECT
setopt HIST_IGNORE_ALL_DUPS
setopt NO_HIST_BEEP
setopt append_history

function cd () { builtin cd $1; ls; }
function pd () { builtin pushd $1; ls; }

executable lesspipe && eval $(lesspipe)
executable aws_zsh_completer.sh && source `which aws_zsh_completer.sh`
if executable dircolors && [[ -f $HOME/.dircolors ]]; then
  eval $(dircolors $HOME/.dircolors)
  zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
else
  export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD
fi

function svndiff() { svn diff "$@" | pygmentize -l diff }
function zle-line-finish() { zle reset-prompt }
executable iconv && function convcn() { iconv -f gb2312 "$@" }
