templates:
  params:
    author-email: tsbattman@gmail.com
    author-name: Thayne Batty
    copyright: ! 'Copyright: 2016-2017 Thayne S. Batty'
    category: Data
    github-username: tsbattman
system-ghc: true
