
---
- name: user
  hosts: all
  gather_facts: no
  vars_files:
    - ~/etc/ansible/vars-aws.yml
  tasks:
    - apt: pkg=zsh state=latest
    - group: name=thayne
    - group: name=data
    - user: name=thayne password={{tsb_pwd}} group=thayne groups=adm,cdrom,sudo,dip,plugdev,audio,video,data shell=/usr/bin/zsh
    - authorized_key: key="{{item}}" user=thayne
      with_file:
        - ~/.ssh/id_rsa.pub

- name: packages
  hosts: all
  gather_facts: no
  tasks:
    - apt: pkg="python-pycurl" state=latest
    - apt_repository: repo={{item}}
      with_items:
        - ppa:staticfloat/juliareleases
        - ppa:staticfloat/julia-deps
        - ppa:x2go/stable
    - apt: pkg={{ item }} state=latest
      with_items:
        - x2goserver
        - x2goserver-xsession
        - xmonad
        - suckless-tools # dmenu
        - vim-gtk
        - rxvt-unicode
        - make
        - llvm
        - clang
        - libgsl0-dev
        - liblapack-dev
        - git
        - ghc
        - julia
        - python-pip

- name: sys cfg
  hosts: sftp
  gather_facts: no
  vars_files:
    - ~/etc/ansible/vars-aws.yml
  tasks:
    - user: name=data group=data password={{data_pwd}}
    - file: path=/mnt/data owner=root group=root mode=755
    - file: path=/mnt/data/mkt owner=data group=data mode=775 state=directory
    - copy: dest=/etc/ssh/sshd_config src=~/config/etc/ssh/sshd_config backup=yes
      notify: restart ssh
  handlers:
    - name: restart ssh
      service: name=ssh state=restarted

