
---
- name: user cfg
  hosts: all
  sudo: yes
  sudo_user: thayne
  gather_facts: no
  tasks:
    - git: repo=git://github.com/Shougo/neobundle.vim dest=~/thirdparty/vim/bundle/neobundle.vim
    - git: repo=git://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh
    - git: repo=git://github.com/tsbattman/config.git dest=~/config
    - file: path=~/config/dot/vim/bundle src=~/thirdparty/vim/bundle state=link
    - command: chdir=~/config ./configmapper.sh
    - pip: name={{item}} state=latest extra_args="--user"
      with_items:
        - git-up
